### ISSUE TITLE
Laravel 5.8 compatibility

### ISSUE THREAD

**Issue by ubiteck** [ixudra/wizard#1]
First of all thanks for you package. It is very useful in my development. 
I'm currently migrating to Laravel 5.8 and I'm having trouble with the composer. The following line

`
"laravelcollective/html": "~5.2",
` 

in the composer is incompatible with the release 5.8 or Laravel

Thanks in advance

**Comment by elimentz** [comment]
I tried this for myself and I can install this package in a Laravel 5.8 project without a problem. I think it's some other conflict in your project that is causing the issue here. As far as I can tell, everything works as intended. Maybe if you show me your console output from the `composer update` command, I can see what is actually going on?
